### ISSUE TITLE
Get org.apache.spark.SparkException when using order by

### ISSUE THREAD

**Issue by hoffmann99** [Huawei-Spark/hbase#14]
[1] Hbase Table

grade            int
class            int
subject          string  
teacher _name    string
teacher _age     int

keyCols : grade,class,subject

SQL:
CREATE TABLE spark_teacher_3key(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher_3key, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);

DATA:

1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25

DataFrame:
val teachers: DataFrame = hbaseContext.sql("Select \* from spark_teacher_3key_df")
 teachers.orderBy('grade.asc, 'class.asc).show(3) 

Exception info:
Caused by: org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.SparkContext.<init>(SparkContext.scala:81)
ScalaDF$.main(ScalaDF.scala:25)
ScalaDF.main(ScalaDF.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:601)
org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:664)
org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:169)
org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:192)
org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:111)
org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
    at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$1.apply(SparkContext.scala:2083)
    at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$1.apply(SparkContext.scala:2065)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:2065)
    at org.apache.spark.SparkContext$.setActiveContext(SparkContext.scala:2151)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:2023)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:135)
    at org.apache.spark.sql.test.LocalSQLContext.<init>(TestSQLContext.scala:29)
    at org.apache.spark.sql.test.TestSQLContext$.<init>(TestSQLContext.scala:55)
    at org.apache.spark.sql.test.TestSQLContext$.<clinit>(TestSQLContext.scala)

**Comment by xinyunh** [comment]
Fixed and merged into master (https://github.com/Huawei-Spark/SparkSQL-on-HBase/commit/c4afac0d837724d848de8631a847e79fea84f3da)

Thanks!

**Comment by xinyunh** [comment]
Hi @hoffmann99,

I can not reproduce this exception using the same data and  SQL.
May you double check it?

**Comment by hoffmann99** [comment]
I check many times today, it still have this problem.Even I set spark.driver.allowMultipleContexts true, it still have this problem

**Comment by yzhou2001** [comment]
@hoffmann99  You may ask a different person, Mr. Pei for example,  to double check. Thanks.

**Comment by hoffmann99** [comment]
yes, we check it together with pei zhongshuai

**Comment by xinyunh** [comment]
@hoffmann99, I will recheck it tomorrow. BTW, may you give me your phone number? Yours or Doingdone's.

**Comment by hoffmann99** [comment]
@xinyunh  @yzhou2001  this problem also happens in sparksql. This should be the problem of SparkSql.
I Closed this problem.
